/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReportIdImport } from './routes/report.$id'
import { Route as ReadyIdImport } from './routes/ready.$id'
import { Route as MemoIdImport } from './routes/memo.$id'
import { Route as MakeIdImport } from './routes/make.$id'
import { Route as HistoryIdImport } from './routes/history.$id'
import { Route as EduIdImport } from './routes/edu.$id'
import { Route as CareMemoIdImport } from './routes/care-memo.$id'

// Create Virtual Routes

const CareLazyImport = createFileRoute('/care')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const CareLazyRoute = CareLazyImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/care.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ReportIdRoute = ReportIdImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => rootRoute,
} as any)

const ReadyIdRoute = ReadyIdImport.update({
  id: '/ready/$id',
  path: '/ready/$id',
  getParentRoute: () => rootRoute,
} as any)

const MemoIdRoute = MemoIdImport.update({
  id: '/memo/$id',
  path: '/memo/$id',
  getParentRoute: () => rootRoute,
} as any)

const MakeIdRoute = MakeIdImport.update({
  id: '/make/$id',
  path: '/make/$id',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIdRoute = HistoryIdImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRoute,
} as any)

const EduIdRoute = EduIdImport.update({
  id: '/edu/$id',
  path: '/edu/$id',
  getParentRoute: () => rootRoute,
} as any)

const CareMemoIdRoute = CareMemoIdImport.update({
  id: '/care-memo/$id',
  path: '/care-memo/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareLazyImport
      parentRoute: typeof rootRoute
    }
    '/care-memo/$id': {
      id: '/care-memo/$id'
      path: '/care-memo/$id'
      fullPath: '/care-memo/$id'
      preLoaderRoute: typeof CareMemoIdImport
      parentRoute: typeof rootRoute
    }
    '/edu/$id': {
      id: '/edu/$id'
      path: '/edu/$id'
      fullPath: '/edu/$id'
      preLoaderRoute: typeof EduIdImport
      parentRoute: typeof rootRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdImport
      parentRoute: typeof rootRoute
    }
    '/make/$id': {
      id: '/make/$id'
      path: '/make/$id'
      fullPath: '/make/$id'
      preLoaderRoute: typeof MakeIdImport
      parentRoute: typeof rootRoute
    }
    '/memo/$id': {
      id: '/memo/$id'
      path: '/memo/$id'
      fullPath: '/memo/$id'
      preLoaderRoute: typeof MemoIdImport
      parentRoute: typeof rootRoute
    }
    '/ready/$id': {
      id: '/ready/$id'
      path: '/ready/$id'
      fullPath: '/ready/$id'
      preLoaderRoute: typeof ReadyIdImport
      parentRoute: typeof rootRoute
    }
    '/report/$id': {
      id: '/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof ReportIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/care': typeof CareLazyRoute
  '/care-memo/$id': typeof CareMemoIdRoute
  '/edu/$id': typeof EduIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/make/$id': typeof MakeIdRoute
  '/memo/$id': typeof MemoIdRoute
  '/ready/$id': typeof ReadyIdRoute
  '/report/$id': typeof ReportIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/care': typeof CareLazyRoute
  '/care-memo/$id': typeof CareMemoIdRoute
  '/edu/$id': typeof EduIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/make/$id': typeof MakeIdRoute
  '/memo/$id': typeof MemoIdRoute
  '/ready/$id': typeof ReadyIdRoute
  '/report/$id': typeof ReportIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/care': typeof CareLazyRoute
  '/care-memo/$id': typeof CareMemoIdRoute
  '/edu/$id': typeof EduIdRoute
  '/history/$id': typeof HistoryIdRoute
  '/make/$id': typeof MakeIdRoute
  '/memo/$id': typeof MemoIdRoute
  '/ready/$id': typeof ReadyIdRoute
  '/report/$id': typeof ReportIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/care'
    | '/care-memo/$id'
    | '/edu/$id'
    | '/history/$id'
    | '/make/$id'
    | '/memo/$id'
    | '/ready/$id'
    | '/report/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/care'
    | '/care-memo/$id'
    | '/edu/$id'
    | '/history/$id'
    | '/make/$id'
    | '/memo/$id'
    | '/ready/$id'
    | '/report/$id'
  id:
    | '__root__'
    | '/'
    | '/care'
    | '/care-memo/$id'
    | '/edu/$id'
    | '/history/$id'
    | '/make/$id'
    | '/memo/$id'
    | '/ready/$id'
    | '/report/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CareLazyRoute: typeof CareLazyRoute
  CareMemoIdRoute: typeof CareMemoIdRoute
  EduIdRoute: typeof EduIdRoute
  HistoryIdRoute: typeof HistoryIdRoute
  MakeIdRoute: typeof MakeIdRoute
  MemoIdRoute: typeof MemoIdRoute
  ReadyIdRoute: typeof ReadyIdRoute
  ReportIdRoute: typeof ReportIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CareLazyRoute: CareLazyRoute,
  CareMemoIdRoute: CareMemoIdRoute,
  EduIdRoute: EduIdRoute,
  HistoryIdRoute: HistoryIdRoute,
  MakeIdRoute: MakeIdRoute,
  MemoIdRoute: MemoIdRoute,
  ReadyIdRoute: ReadyIdRoute,
  ReportIdRoute: ReportIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/care",
        "/care-memo/$id",
        "/edu/$id",
        "/history/$id",
        "/make/$id",
        "/memo/$id",
        "/ready/$id",
        "/report/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/care": {
      "filePath": "care.lazy.tsx"
    },
    "/care-memo/$id": {
      "filePath": "care-memo.$id.tsx"
    },
    "/edu/$id": {
      "filePath": "edu.$id.tsx"
    },
    "/history/$id": {
      "filePath": "history.$id.tsx"
    },
    "/make/$id": {
      "filePath": "make.$id.tsx"
    },
    "/memo/$id": {
      "filePath": "memo.$id.tsx"
    },
    "/ready/$id": {
      "filePath": "ready.$id.tsx"
    },
    "/report/$id": {
      "filePath": "report.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
