/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MemoIdImport } from './routes/memo.$id'
import { Route as HistoryIdImport } from './routes/history.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MemoIdRoute = MemoIdImport.update({
  id: '/memo/$id',
  path: '/memo/$id',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIdRoute = HistoryIdImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdImport
      parentRoute: typeof rootRoute
    }
    '/memo/$id': {
      id: '/memo/$id'
      path: '/memo/$id'
      fullPath: '/memo/$id'
      preLoaderRoute: typeof MemoIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/history/$id': typeof HistoryIdRoute
  '/memo/$id': typeof MemoIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/history/$id': typeof HistoryIdRoute
  '/memo/$id': typeof MemoIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/history/$id': typeof HistoryIdRoute
  '/memo/$id': typeof MemoIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/history/$id' | '/memo/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/history/$id' | '/memo/$id'
  id: '__root__' | '/' | '/history/$id' | '/memo/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  HistoryIdRoute: typeof HistoryIdRoute
  MemoIdRoute: typeof MemoIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  HistoryIdRoute: HistoryIdRoute,
  MemoIdRoute: MemoIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/history/$id",
        "/memo/$id"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/history/$id": {
      "filePath": "history.$id.tsx"
    },
    "/memo/$id": {
      "filePath": "memo.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
